name: Add URLs in Sitemaps v.2

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Sitemap URLs
        run: |
          # Get the current directory
          dir=$(pwd)

          # Get the GitHub repository name from the current directory
          repo_name=$(basename "$dir" | tr '[:upper:]' '[:lower:]')

          # Walk through the current directory and update .xml files
          find . -type f -name '*.xml' -print0 | while IFS= read -r -d '' file; do
            echo "Processing $file"
            sed -i "s|loc>/|loc>https://$repo_name/|g" "$file"
          done

          # Ensure GitHub user is configured
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'

          # Add changes to git
          git add .

          # Commit changes
          git commit -m 'Update XML files'

          # Push changes to the repository
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
